apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-uv-fastapi
spec:
  hostAPI: "http://192.168.2.51:31000"
  resyncInterval: 10
  authentication:
    universalAuth:
      credentialsRef:
        secretName: universal-auth-credentials 
        secretNamespace: default
      secretsScope: 
        projectId: "128ec5f1-3d60-4cf6-972b-23b38c2915e8"
        envSlug: dev
        secretsPath: "/UV"
        recursive: true

  managedKubeSecretReferences:
    - secretName: uv-fastapi-default
      secretNamespace: default
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true

        